### ISSUE TITLE
Docker-compose up fails

### ISSUE THREAD

**Issue by bachstatter** [kaleb-keny/staking_ratio_grants_council#1]
Hey!

I added a config file and ran `docker-compose up`. The ` pip install -r env/requirements.txt` step failed

<img width="702" alt="image" src="https://user-images.githubusercontent.com/5688912/184322864-0b474fb1-5884-445b-a4c3-8d569e9f82dc.png">

**Comment by kaleb-keny** [comment]
can you retry please hopefully this https://github.com/kaleb-keny/staking_ratio_grants_council/commit/52990633f6f495f74692aeaef4137d0fa56d5cde helps 🤔 pretty weird docker doesn't work across machines

**Comment by bachstatter** [comment]
New error. Sorry for wall of text:

```
#8 18.91 Collecting PyQt5
#8 18.94   Downloading PyQt5-5.15.7.tar.gz (3.2 MB)
#8 19.47      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 6.1 MB/s eta 0:00:00
#8 20.64   Installing build dependencies: started
#8 32.85   Installing build dependencies: finished with status 'done'
#8 32.87   Getting requirements to build wheel: started
#8 33.05   Getting requirements to build wheel: finished with status 'done'
#8 33.05   Preparing metadata (pyproject.toml): started
#8 33.21   Preparing metadata (pyproject.toml): finished with status 'error'
#8 33.22   error: subprocess-exited-with-error
#8 33.22
#8 33.22   × Preparing metadata (pyproject.toml) did not run successfully.
#8 33.22   │ exit code: 1
#8 33.22   ╰─> [29 lines of output]
#8 33.22       Traceback (most recent call last):
#8 33.22         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
#8 33.22           hook = backend.prepare_metadata_for_build_wheel
#8 33.22       AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
#8 33.22
#8 33.22       During handling of the above exception, another exception occurred:
#8 33.22
#8 33.22       Traceback (most recent call last):
#8 33.22         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#8 33.22           main()
#8 33.22         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#8 33.22           json_out['return_val'] = hook(**hook_input['kwargs'])
#8 33.22         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
#8 33.22           whl_basename = backend.build_wheel(metadata_directory, config_settings)
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/sipbuild/api.py", line 47, in build_wheel
#8 33.22           arguments=_convert_config_settings(config_settings))
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
#8 33.22           project.setup(pyproject, tool, tool_description)
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 584, in setup
#8 33.22           self.apply_user_defaults(tool)
#8 33.22         File "project.py", line 69, in apply_user_defaults
#8 33.22           super().apply_user_defaults(tool)
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
#8 33.22           super().apply_user_defaults(tool)
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
#8 33.22           self.builder.apply_user_defaults(tool)
#8 33.22         File "/tmp/pip-build-env-u9x90gtw/overlay/lib/python3.7/site-packages/pyqtbuild/builder.py", line 68, in apply_user_defaults
#8 33.22           "specify a working qmake or add it to PATH")
#8 33.22       sipbuild.pyproject.PyProjectOptionException
#8 33.22       [end of output]
#8 33.22
#8 33.22   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 33.22 error: metadata-generation-failed
#8 33.22
#8 33.22 × Encountered error while generating package metadata.
#8 33.22 ╰─> See above for output.
#8 33.22
#8 33.22 note: This is an issue with the package mentioned above, not pip.
#8 33.22 hint: See above for details.
#8 33.24 WARNING: You are using pip version 22.0.4; however, version 22.2.2 is available.
#8 33.24 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
```

**Comment by kaleb-keny** [comment]
@bachstatter can you please try this branch? https://github.com/kaleb-keny/staking_ratio_grants_council 
I believe I needed to specify the usage of an ubuntu image in docker, which is done normally in the Dockerfile.
